# Generated by Django 3.2.2 on 2021-05-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendgrid_newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='contents',
            field=models.FileField(upload_to='uploaded_newsletters/'),
        ),
    ]
